# Generated by Django 4.2.14 on 2024-07-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JimenezQuispeHubertJared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.TextField()),
                ('sexo', models.TextField()),
                ('fecha_de_registro', models.TextField()),
            ],
        ),
    ]
